apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "bitcoind.fullname" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "bitcoind.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "bitcoind.name" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.configurationFile }}
      initContainers:
        - name: copy-bitcoind-config
          image: busybox
          command: ['sh', '-c', 'cp /configmap/bitcoin.conf /bitcoin/.bitcoin/bitcoin.conf']
          volumeMounts:
            - name: configmap
              mountPath: /configmap
            - name: config
              mountPath: /bitcoin/.bitcoin/
      {{- end }}
      containers:
        - name: {{ template "bitcoind.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
          ports:
            - name: rpc
              containerPort: {{ .Values.service.rpcPort }}
            - name: p2p
              containerPort: {{ .Values.service.p2pPort }}
            - name: testnet
              containerPort: {{ .Values.service.testnetPort }}
            - name: testnetp2pport
              containerPort: {{ .Values.service.testnetP2pPort }}
          volumeMounts:
            - name: data
              mountPath: /bitcoin
            {{- if .Values.configurationFile }}
            - name: config
              mountPath: /bitcoin/.bitcoin/bitcoin.conf
              subPath: bitcoin.conf
            {{- end }}
        {{- if .Values.lnd.enabled }}
        - name: lnd
          image: "{{ .Values.lnd.image.repository }}:{{ .Values.lnd.image.tag }}"
          imagePullPolicy: {{ .Values.lnd.image.pullPolicy | quote }}
          ports:
          - name: lnd-rpc
            containerPort: {{ .Values.lnd.service.rpcPort }}
          - name: lnd-grpc
            containerPort: {{ .Values.lnd.service.grpcPort }}
          command:
            - 'lnd'
            - --bitcoin.active
            - --bitcoin.testnet
            - --bitcoin.node=bitcoind
            - --bitcoind.dir=/bitcoin/.bitcoin
            - --debuglevel=debug
          resources:
{{ toYaml .Values.lnd.resources | indent 12 }}
          volumeMounts:
            - name: data
              mountPath: /bitcoin
            - name: lnd-data
              mountPath: "/root/.lnd"
            {{- if .Values.configurationFile }}
            - name: config
              mountPath: /bitcoin/.bitcoin/bitcoin.conf
              subPath: bitcoin.conf
            {{- end }}
          {{- if .Values.lnd.cliContainer }}
        - name: lncli
          image: "{{ .Values.lnd.image.repository }}:{{ .Values.lnd.image.tag }}"
          imagePullPolicy: {{ .Values.lnd.image.pullPolicy | quote }}
          command:
            - 'sleep'
            - '99999999'
          volumeMounts:
            - name: data
              mountPath: /bitcoin
            - name: lnd-data
              mountPath: "/root/.lnd"
            {{- if .Values.configurationFile }}
            - name: config
              mountPath: /bitcoin/.bitcoin/bitcoin.conf
              subPath: bitcoin.conf
            {{- end }}
          {{- end }}
          {{- if .Values.lnd.lndConfStaticServer }}
        - name: lnd-conf
          image: "abhin4v/hastatic:latest"
          workingDir: /lnd
          command: ["/usr/bin/hastatic"]
          ports:
          - name: static
            containerPort: 3000
          volumeMounts:
            - name: lnd-data
              mountPath: "/lnd"
            {{- if .Values.configurationFile }}
            - name: config
              mountPath: /bitcoin/.bitcoin/bitcoin.conf
              subPath: bitcoin.conf
            {{- end }}
          {{- end }}
        {{- end }}
      volumes:
        {{- if .Values.configurationFile }}
        - name: config
          emptyDir: {}
        - name: configmap
          configMap:
            name: {{ template "bitcoind.fullname" . }}
        {{- end }}
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim | default (include "bitcoind.fullname" .) }}
        {{- else }}
          emptyDir: {}
        {{- end }}
        - name: lnd-data
        {{- if .Values.lnd.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ template "bitcoind.fullname" . }}-lnd
        {{- else }}
          emptyDir: {}
        {{- end -}}