{{- if .Values.lnd.persistence.enabled }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "bitcoind.fullname" . }}-lnd
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - {{ .Values.lnd.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.lnd.persistence.size | quote }}
{{- if .Values.lnd.persistence.storageClass }}
{{- if (eq "-" .Values.lnd.persistence.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.lnd.persistence.storageClass }}"
{{- end }}
{{- end }}
{{- end }}
