apiVersion: v1
kind: Service
metadata:
  name: {{ template "bitcoind.fullname" . }}
  labels:
    app: {{ template "bitcoind.name" . }}
    chart: {{ template "bitcoind.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: rpc
      port: {{ .Values.service.rpcPort }}
      targetPort: rpc
    - name: p2p
      port: {{ .Values.service.p2pPort }}
      targetPort: p2p
    - name: testnet
      port: {{ .Values.service.testnetPort }}
    - name: testnet-p2p
      port: {{ .Values.service.testnetP2pPort }}
    {{- if .Values.lnd.enabled }}
    - name: lnd-rpc
      port: {{ .Values.lnd.service.rpcPort }}
      targetPort: lnd-rpc
    - name: lnd-grpc
      port: {{ .Values.lnd.service.grpcPort }}
      targetPort: lnd-grpc
    {{- if .Values.lnd.lndConfStaticServer }}
    - name: static
      port: 3000
      targetPort: static
    {{- end }}
    {{- end }}
  selector:
    app: {{ template "bitcoind.name" . }}
    release: {{ .Release.Name }}
